import { supabase } from './client';
import { backupSummary, validateBackup } from './snapshot';
import type { Backup, BackupSummary } from './snapshot';
export type BackupRow = { id: string; owner_id: string; captured_at: string; created_at: string; summary: BackupSummary };
async function account() { if (!supabase) throw new Error('Native secure account storage is required.'); const result = await supabase.auth.getUser(); if (result.error || !result.data.user) throw new Error('Sign in and reconnect before using cloud backups.'); return { client: supabase, userId: result.data.user.id }; }
export async function listBackups(): Promise<BackupRow[]> { const { client, userId } = await account(); const { data, error } = await client.from('on_track_backups').select('id,owner_id,captured_at,created_at,summary').eq('owner_id', userId).order('created_at', { ascending: false }).limit(30); if (error) throw error; return data as BackupRow[]; }
export async function saveBackup(backup: Backup, expectedUserId: string): Promise<BackupRow> { const { client, userId } = await account(); if (userId !== expectedUserId) throw new Error('Account changed. Retry backup from your intended account.'); const payload = validateBackup(backup); const { data, error } = await client.from('on_track_backups').insert({ owner_id: userId, captured_at: payload.capturedAt, schema_version: 1, payload, summary: backupSummary(payload) }).select('id,owner_id,captured_at,created_at,summary').single(); if (error) throw error; return data as BackupRow; }
export async function getBackup(id: string, expectedUserId: string): Promise<Backup> { const { client, userId } = await account(); if (userId !== expectedUserId) throw new Error('Account changed. Refresh your backup list.'); const { data, error } = await client.from('on_track_backups').select('payload').eq('owner_id', userId).eq('id', id).single(); if (error) throw error; return validateBackup(data.payload); }
export async function deleteBackup(id: string): Promise<void> { const { client, userId } = await account(); const { error } = await client.from('on_track_backups').delete().eq('id', id).eq('owner_id', userId); if (error) throw error; }
