export type Facts = { from: string; through: string; elapsedDays: number; foodComplete: number; foodUnconfirmed: number; workouts: number; creatine: number; withinTarget: number; overTarget: number; unknownTarget: number; revisions: number; revisedDays: number; forgottenFoodDays: string[]; trend: number | null; measuredDays: number };
function date(value: unknown): value is string { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const d = new Date(value + 'T12:00:00Z'); return Number.isFinite(d.getTime()) && d.toISOString().slice(0, 10) === value; }
export function validateFacts(value: unknown): Facts {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Invalid facts.'); const f = value as Facts;
  const allowed = ['from','through','elapsedDays','foodComplete','foodUnconfirmed','workouts','creatine','withinTarget','overTarget','unknownTarget','revisions','revisedDays','forgottenFoodDays','trend','measuredDays'];
  if (Object.keys(f).some(key => !allowed.includes(key)) || Object.keys(f).length !== allowed.length || !date(f.from) || !date(f.through) || f.from > f.through) throw new Error('Invalid facts.');
  if (!Number.isInteger(f.elapsedDays) || f.elapsedDays < 1 || f.elapsedDays > 14 || (Date.parse(f.through) - Date.parse(f.from)) / 86400000 + 1 !== f.elapsedDays) throw new Error('Invalid date window.');
  for (const key of ['foodComplete','foodUnconfirmed','workouts','creatine','withinTarget','overTarget','unknownTarget','revisedDays'] as const) if (!Number.isInteger(f[key]) || f[key] < 0 || f[key] > f.elapsedDays) throw new Error('Invalid counts.');
  if (f.foodComplete + f.foodUnconfirmed !== f.elapsedDays || f.withinTarget + f.overTarget + f.unknownTarget !== f.elapsedDays || !Number.isInteger(f.revisions) || f.revisions < 0 || f.revisions > 1000 || f.revisedDays > f.revisions || !Array.isArray(f.forgottenFoodDays) || f.forgottenFoodDays.length > f.revisedDays || f.forgottenFoodDays.some(d => !date(d) || d < f.from || d > f.through) || new Set(f.forgottenFoodDays).size !== f.forgottenFoodDays.length || !Number.isInteger(f.measuredDays) || f.measuredDays < 0 || f.measuredDays > 7 || !(f.trend === null || typeof f.trend === 'number' && Number.isFinite(f.trend) && f.trend > 0 && f.trend <= 2000)) throw new Error('Invalid facts.');
  if (f.measuredDays === 0 && f.trend !== null) throw new Error('Trend needs readings.'); return JSON.parse(JSON.stringify(f));
}
export function responseText(body: unknown): string { const b=body as { output?: { content?: { type?: string; text?: string }[] }[] }; if (!Array.isArray(b?.output)) return ''; return b.output.flatMap(item => Array.isArray(item.content) ? item.content.filter(c => c.type === 'output_text' && typeof c.text === 'string').map(c => c.text!) : []).join('\n').slice(0,4000); }
export type CoachPorts = { configured: () => boolean; verifyUser: (token: string) => Promise<boolean>; quota: (token: string) => Promise<boolean>; generate: (facts: Facts) => Promise<string> };
const headers = { 'Content-Type':'application/json', 'Access-Control-Allow-Origin':'*', 'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type', 'Access-Control-Allow-Methods':'POST, OPTIONS', 'Cache-Control':'no-store' };
const json=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers});
async function boundedJson(req: Request): Promise<unknown> { if (!req.body) throw new Error('Missing body'); const reader=req.body.getReader();const chunks:Uint8Array[]=[];let size=0;try { while(true) { const next=await reader.read();if(next.done)break;size+=next.value.length;if(size>8192){await reader.cancel();throw new Error('Request too large');}chunks.push(next.value); } }finally{reader.releaseLock();}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return JSON.parse(new TextDecoder().decode(bytes)); }
export function coachHandler(ports: CoachPorts) { return async(req: Request): Promise<Response> => {
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return json(405,{error:'POST required.'});
  const auth=req.headers.get('authorization');if(!auth?.startsWith('Bearer ')||auth.length>8192)return json(401,{error:'Sign in first.'});const token=auth.slice(7);let verified=false;try{verified=await ports.verifyUser(token);}catch{return json(401,{error:'Session could not be verified.'});}if(!verified)return json(401,{error:'Invalid session.'});
  let facts:Facts;try{const input=await boundedJson(req) as {mode?:unknown;facts?:unknown};if(!input||input.mode!=='real'||Object.keys(input).some(k=>k!=='mode'&&k!=='facts'))return json(400,{error:'Real summary facts only. No demo data, prompts, or photos.'});facts=validateFacts(input.facts);}catch{return json(400,{error:'Invalid or oversized summary.'});}
  if(!ports.configured())return json(503,{error:'Cloud AI is not configured. Use the local review.'});
  try{if(!await ports.quota(token))return json(429,{error:'Daily review limit reached (5 attempts per UTC day).'});}catch{return json(503,{error:'Review limit could not be checked. Try later.'});}
  try{const review=await ports.generate(facts);if(!review)return json(502,{error:'No review returned. Use the local review.'});return json(200,{review});}catch{return json(502,{error:'AI request failed. Use the local review.'});}
}; }
