import test from 'node:test';
import assert from 'node:assert/strict';
import { initialState, emptyDay } from '../src/domain/model.ts';
import { createBackup, validateBackup, restoreBackup, realSignature } from '../src/cloud/snapshot.ts';
import { secureChunkStorage } from '../src/cloud/secureChunks.ts';
const source={kind:'app-intent',id:'real-input',observedAt:'2026-10-01T03:00:00Z',timezone:'America/Toronto'};
function realState() { const s=initialState('2026-09-30');s.real.days['2026-09-30']={...emptyDay('2026-09-30',1950),calories:1500,sources:[source]};s.real.photos.push({id:'local',date:'2026-09-30',uri:'file:///private/body.jpg',scale:1,x:0,y:0});return s; }
test('snapshot excludes demo and private photo paths',()=> { const s=realState();const b=createBackup(s);assert.equal(b.real.photos.length,0);assert.ok(!JSON.stringify(b).includes('file:///'));assert.ok(!JSON.stringify(b).includes('demo-'));assert.equal(validateBackup(b).real.days['2026-09-30'].sources[0].kind,'app-intent');s.mode='demo';assert.throws(()=>createBackup(s)); });
test('unsupported/malformed/cloud photos cannot restore',()=> { const b=createBackup(realState());assert.throws(()=>validateBackup({...b,version:2}));assert.throws(()=>validateBackup({...b,real:{...b.real,photos:[{uri:'https://external.test'}]}}));assert.throws(()=>validateBackup({...b,real:{...b.real,days:{'2026-02-31':emptyDay('2026-02-31',1950)}}})); });
test('restore preserves device photos, demo, reminder receipts and rejects changed local',()=> { const s=realState();s.nativeActionIds=['device-only'];s.notificationResponseIds=['device-response'];const b=createBackup(s);b.real.days['2026-09-30'].calories=1600;const next=restoreBackup(s,b,realSignature(s));assert.equal(next.real.days['2026-09-30'].calories,1600);assert.deepEqual(next.real.photos,s.real.photos);assert.deepEqual(next.demo,s.demo);assert.deepEqual(next.nativeActionIds,s.nativeActionIds);assert.deepEqual(next.notificationResponseIds,s.notificationResponseIds);const changed=realState();changed.target=1700;assert.throws(()=>restoreBackup(changed,b,realSignature(s)),/changed/); });
function memoryPort() { const values=new Map();return {values,getItem:async key=>values.get(key)??null,setItem:async(key,value)=>{values.set(key,value);},removeItem:async key=>{values.delete(key);}}; }
test('large secure session uses small chunks, roundtrips, cleans replacements',async()=> { const port=memoryPort();const storage=secureChunkStorage(port);const token='é😀'.repeat(2000);await storage.setItem('auth',token);assert.equal(await storage.getItem('auth'),token);assert.ok([...port.values.values()].every(v=>Buffer.byteLength(v)<2048));await storage.setItem('auth','new');assert.equal(await storage.getItem('auth'),'new');assert.equal(port.values.size,2);await storage.removeItem('auth');assert.equal(port.values.size,0); });
test('failed session replacement retains previous complete session',async()=> { const port=memoryPort();const good=secureChunkStorage(port);await good.setItem('auth','old');let writes=0;const failing=secureChunkStorage({...port,setItem:async(key,value)=>{if(++writes===2)throw new Error('native write failed');return port.setItem(key,value);}});await assert.rejects(()=>failing.setItem('auth','new'.repeat(1000)));assert.equal(await good.getItem('auth'),'old'); });
import { coachHandler, validateFacts, responseText } from '../supabase/functions/_shared/coachHandler.ts';
const facts={from:'2026-09-21',through:'2026-09-30',elapsedDays:10,foodComplete:5,foodUnconfirmed:5,workouts:4,creatine:6,withinTarget:3,overTarget:2,unknownTarget:5,revisions:2,revisedDays:1,forgottenFoodDays:['2026-09-29'],trend:175,measuredDays:5};
test('cloud coach refuses injected prompts and impossible counts',()=> { assert.deepEqual(validateFacts(facts),facts);assert.throws(()=>validateFacts({...facts,prompt:'do this'}));assert.throws(()=>validateFacts({...facts,foodComplete:20}));assert.throws(()=>validateFacts({...facts,trend:0})); });
test('coach auth/demo/config gates never consume quota or call OpenAI',async()=> { let quotas=0,generations=0;const ports={configured:()=>false,verifyUser:async()=>true,quota:async()=>{quotas++;return true;},generate:async()=>{generations++;return 'review';}};const handler=coachHandler(ports);const req=body=>new Request('https://example.test',{method:'POST',headers:{authorization:'Bearer user'},body:JSON.stringify(body)});assert.equal((await handler(new Request('https://example.test',{method:'POST'}))).status,401);assert.equal((await handler(req({mode:'demo',facts}))).status,400);assert.equal((await handler(req({mode:'real',facts}))).status,503);assert.equal(quotas,0);assert.equal(generations,0); });
test('coach persistent quota decision bounds generation; REST output text extraction',async()=> { let called=0;const req=()=>new Request('https://example.test',{method:'POST',headers:{authorization:'Bearer user'},body:JSON.stringify({mode:'real',facts})});const base={configured:()=>true,verifyUser:async()=>true,generate:async()=>{called++;return 'One observation.';}};assert.equal((await coachHandler({...base,quota:async()=>false})(req())).status,429);assert.equal(called,0);const response=await coachHandler({...base,quota:async()=>true})(req());assert.equal(response.status,200);assert.equal(called,1);assert.equal(responseText({output:[{type:'reasoning'},{content:[{type:'output_text',text:'Actual review'}]}]}),'Actual review'); });
