import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyData,emptyDay,initialState,addDays } from '../src/domain/model.ts';
import {periodSummary,milestoneProgress,shareSummary,trendSeries} from '../src/domain/progress.ts';
const today='2026-10-01';
function reading(date,pounds) { return {id:date,date,pounds,source:{kind:'manual',id:date,observedAt:date+'T12:00:00Z',timezone:'America/Toronto'}}; }
test('empty real summary reports unknown coverage, excludes future, no fabricated calorie mean',()=>{const data=emptyData();const period=periodSummary(data,today);assert.equal(period.dates[0],'2026-09-21');assert.equal(period.dates.length,11);assert.equal(period.completeDays,0);assert.equal(period.meanCompleteCalories,null);assert.ok(period.totals.every(t=>t.known===0&&t.unknown===11));});
test('complete over target log counts honesty; low incomplete total stays unknown',()=>{const data=emptyData();data.days[today]={...emptyDay(today,1950),calories:2200,food:true};data.days['2026-09-30']={...emptyDay('2026-09-30',1950),calories:1200};const p=periodSummary(data,today);assert.equal(p.totals[2].done,1);assert.equal(p.totals[3].known,1);assert.equal(p.totals[3].done,0);assert.equal(p.meanCompleteCalories,2200);assert.equal(p.completeCalorieDays,1);});
test('revision counts retain multiple edits and distinct dates separately',()=>{const data=emptyData();data.revisions=[{date:today},{date:today},{date:'2026-09-30'},{date:'2026-09-01'},{date:'2026-10-04'}];const p=periodSummary(data,today);assert.equal(p.revisionCount,3);assert.equal(p.revisedDays,2);});
test('known No reports coverage without awarding a success',()=>{const data=emptyData();data.days[today]={...emptyDay(today,1950),calories:2000,food:false,workout:false,creatine:false};const p=periodSummary(data,today);assert.equal(p.answeredDays,1);assert.equal(p.completeDays,0);assert.ok(p.totals.every(t=>t.known===1&&t.done===0));});
test('trend display requires distinct measured days rather than repeat readings',()=>{const data=emptyData();data.weights=Array.from({length:10},(_,i)=>({...reading(today,170),id:String(i)}));const s=initialState(today);s.goal=155;s.milestones=[172];const p=milestoneProgress(data,s,today);assert.equal(p.current.coverage,1);assert.equal(p.qualified,false);assert.deepEqual(p.reached,[]);assert.equal(p.fraction,null);});
test('progress uses earliest qualified trend baseline and sorts checkpoint targets',()=>{const data=emptyData();for(let i=0;i<14;i++)data.weights.push(reading(addDays(today,i-13),180-i));const s=initialState(today);s.goal=155;s.milestones=[165,172,170,172];const p=milestoneProgress(data,s,today);assert.equal(p.baselineDate,addDays(today,-10));assert.equal(p.baseline,178.5);assert.equal(p.current.average,170);assert.equal(p.next,165);assert.deepEqual(p.reached,[172,170]);assert.ok(p.fraction>0&&p.fraction<1);});
test('baseline at or below goal never divides by zero; future weights excluded',()=>{const data=emptyData();for(let i=0;i<7;i++)data.weights.push(reading(addDays(today,i-6),155));data.weights.push(reading('2026-10-10',100));const s=initialState(today);s.goal=155;const p=milestoneProgress(data,s,today);assert.equal(p.fraction,null);assert.equal(p.current.average,155);assert.equal(p.next,null);});
test('sharing preview labels demo, coverage and uncertainty and excludes private photo URI',()=>{const s=initialState(today);s.mode='demo';s.demo.photos=[{uri:'private-photo-secret'}];const message=shareSummary(s.demo,s,today);assert.ok(message.startsWith('DEMO'));assert.ok(message.includes('reported'));assert.ok(message.includes('Unknown checks remain unknown'));assert.ok(!message.includes('private-photo-secret'));});

test('all-time chart includes old history; narrow ranges exclude old and future readings',()=>{const data=emptyData();data.weights=[reading('2026-01-01',180),reading('2026-09-30',172),reading('2026-10-01',171),reading('2026-10-02',160)];assert.equal(trendSeries(data,today,'all')[0].date,'2026-01-01');assert.equal(trendSeries(data,today,28)[0].date,'2026-09-30');assert.ok(!trendSeries(data,today,'all').some(p=>p.date>today));});
