import test from 'node:test';
import assert from 'node:assert/strict';
import { initialState, setAnswer, setCalories, confirmFood, localDate } from '../src/domain/model.ts';
import { planReminders, completeReminder, snoozePlan, reconciliation, readPayload } from '../src/domain/reminders.ts';
const zone = Intl.DateTimeFormat().resolvedOptions().timeZone;
function enabled() { const state = initialState('2026-09-30'); state.reminders.forEach(r => { r.enabled = true; }); return state; }
const now = new Date(2026, 8, 30, 12);
test('finite horizon stays below iOS 64 limit and demo never schedules', () => { const s = enabled(); const plans = planReminders(s, now); assert.ok(plans.length <= 42); assert.ok(plans.length > 35); assert.equal(new Set(plans.map(p => p.id)).size, plans.length); s.mode = 'demo'; assert.deepEqual(planReminders(s, now), []); });
test('1am reminder retains previous day across midnight and snooze', () => { const s = enabled(); const p = planReminders(s, now).find(p => p.payload.kind === 'food'); assert.equal(p.payload.date, '2026-09-30'); assert.equal(localDate(new Date(p.payload.fireAt)), '2026-10-01'); const snooze = snoozePlan(s, p.payload, new Date(p.payload.fireAt)); assert.equal(snooze.payload.date, p.payload.date); assert.equal(snooze.payload.fireAt, p.payload.fireAt + 1800000); });
test('completion is dated, idempotent, preserves food unknown and source', () => { const s = enabled(); const p = planReminders(s, now).find(p => p.payload.kind === 'workout'); const changed = completeReminder(s, p.payload, new Date(p.payload.fireAt)); assert.equal(changed.real.days[p.payload.date].workout, true); assert.equal(changed.real.days[p.payload.date].food, null); assert.equal(changed.real.days[p.payload.date].sources[0].kind, 'notification'); assert.equal(completeReminder(changed, p.payload, new Date(p.payload.fireAt)), changed); const food = planReminders(s, now).find(p => p.payload.kind === 'food'); assert.equal(completeReminder(s, food.payload), s); });
test('stale preference, disabled, future and demo responses cannot alter records', () => { const s = enabled(); const p = planReminders(s, now).find(p => p.payload.kind === 'workout'); assert.equal(completeReminder(s, p.payload, new Date(2026,8,29)),s); s.reminders.find(r => r.id === 'workout').time = '20:00'; assert.equal(completeReminder(s, p.payload, now), s); s.mode = 'demo'; assert.equal(completeReminder(s, p.payload, now), s); });
test('No resolves habit; partial calories keep review; confirmed food cancels it', () => { const s = enabled(); s.real = setAnswer(s.real,'2026-09-30',null,'workout',false); s.real = setCalories(s.real,'2026-09-30',1950,1400,'test'); const plans = planReminders(s,now); assert.ok(!plans.some(p => p.payload.kind==='workout' && p.payload.date==='2026-09-30')); assert.ok(plans.some(p => p.payload.kind==='food' && p.payload.date==='2026-09-30')); s.real = confirmFood(s.real,'2026-09-30',1950); assert.ok(!planReminders(s,now).some(p => p.payload.kind==='food' && p.payload.date==='2026-09-30')); });
test('snooze bounded twice; resolved, old and changed preferences reject snooze', () => { const s = enabled(); const p = planReminders(s,now).find(p => p.payload.kind==='workout'); const one = snoozePlan(s,p.payload,now); const two = snoozePlan(s,one.payload,now); assert.equal(snoozePlan(s,two.payload,now),null); assert.equal(snoozePlan(s,p.payload,new Date(2026,9,4)),null); s.real=setAnswer(s.real,p.payload.date,null,'workout',true); assert.equal(snoozePlan(s,p.payload,now),null); });
test('reconciliation idempotent, cancels only owned notifications and retains snooze', () => { const s = enabled(); const plans = planReminders(s,now); const snooze = snoozePlan(s,plans.find(p=>p.payload.kind==='workout').payload,now); const existing = [...plans,snooze].map(p=>({id:p.id,payload:p.payload})); existing.push({id:'other-app',payload:null}); assert.equal(reconciliation(s,now,zone,existing,true).add.length,0); const cancelled = reconciliation(s,now,zone,existing,false); assert.equal(cancelled.cancel.length,plans.length+1); assert.ok(!cancelled.cancel.includes('other-app')); });
test('weekend time follows firing calendar day; invalid dates/payloads rejected', () => { const s = enabled(); s.reminders.find(r=>r.id==='food').weekendTime='02:30'; const plans = planReminders(s,new Date(2026,9,2,12)); const saturday=plans.find(p=>p.payload.kind==='food'); assert.equal(new Date(saturday.payload.fireAt).getHours(),2); assert.equal(saturday.payload.date,'2026-10-02'); assert.equal(readPayload({...saturday.payload,date:'2026-02-30'}),null); assert.equal(readPayload({...saturday.payload,owner:'other'}),null); });
test('DST spring skips nonexistent wall time without changing logical date', () => { if(zone!=='America/Toronto') return; const s = enabled(); s.reminders=[{id:'food',label:'Food',time:'02:30',weekendTime:'02:30',dayOffset:-1,enabled:true}]; const plans=planReminders(s,new Date(2026,2,7,12)); assert.ok(!plans.some(p=>localDate(new Date(p.payload.fireAt))==='2026-03-08')); });

test('same identifier with stale preference payload is replaced', () => { const s=enabled(); const plans=planReminders(s,now); const existing=plans.map(p=>({id:p.id,payload:p.payload})); s.reminders.find(r=>r.id==='workout').weekendTime='19:00'; const result=reconciliation(s,now,zone,existing,true); const weekday=plans.find(p=>p.payload.kind==='workout'); assert.ok(result.cancel.includes(weekday.id)); assert.ok(result.add.some(p=>p.id===weekday.id)); });
