import React, { useState } from 'react';
import { Alert, TextInput } from 'react-native';
import { useCloud } from '../store/CloudStore';
import { useApp } from '../store/AppStore';
import { Button, Card, Label, Row, Screen } from '../components/UI';
export default function Account() { const cloud = useCloud(); const { state, palette: p } = useApp(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const field = { minHeight: 48, padding: 12, borderColor: p.line, borderWidth: 1, borderRadius: 12, color: p.text, backgroundColor: p.bg, fontSize: 16 }; const credentialsValid = email.includes('@') && password.length >= 8;
  return <Screen title="Account & backups"><Card><Label>Optional cloud account</Label><Label small>Personal tracking works offline. Cloud snapshots upload only when you choose Backup now. Photos remain on this device.</Label><Label small>{cloud.authReady ? cloud.session?.user.email ?? 'Signed out' : 'Loading secure session…'}</Label><Label small>{cloud.status}</Label>{cloud.error ? <Label>{cloud.error}</Label> : null}</Card>
    {!cloud.available ? <Card><Label>Cloud account requires the native iPhone app.</Label><Label small>Session tokens use secure device storage. No browser fallback.</Label></Card> : !cloud.session ? <Card><TextInput accessibilityLabel="Email" autoCapitalize="none" autoCorrect={false} keyboardType="email-address" textContentType="emailAddress" placeholder="Email" placeholderTextColor={p.muted} value={email} onChangeText={setEmail} style={field} /><TextInput accessibilityLabel="Password" autoCapitalize="none" autoCorrect={false} secureTextEntry textContentType="password" placeholder="Password (at least 8 characters)" placeholderTextColor={p.muted} value={password} onChangeText={setPassword} style={field} /><Row><Button title="Sign in" primary disabled={!credentialsValid || cloud.busy || !cloud.authReady} onPress={() => { void cloud.signIn(email, password).then(() => setPassword('')); }} /><Button title="Create account" disabled={!credentialsValid || cloud.busy || !cloud.authReady} onPress={() => Alert.alert('Create cloud account?', 'Supabase may send a confirmation email. No records are uploaded until you choose Backup now.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Create account', onPress: () => { void cloud.signUp(email, password).then(() => setPassword('')); } }])} /></Row></Card> : <>
      <Card><Button title="Backup now" primary disabled={cloud.busy || state.mode !== 'real'} onPress={() => Alert.alert('Back up personal records?', 'Uploads calorie/weight/check history and targets to your private account. Photos are excluded. This creates a new snapshot; it does not replace a previous one.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Backup now', onPress: () => { void cloud.backupNow(); } }])} /><Button title="Refresh cloud backups" disabled={cloud.busy} onPress={() => { void cloud.refresh(); }} /><Label small>{state.mode === 'demo' ? 'Switch to personal mode to back up or restore. Demo data is never uploaded.' : 'Restore requires preview and explicit confirmation. No automatic sync.'}</Label></Card>
      {cloud.backups.map(row => <Card key={row.id}><Label>{new Date(row.captured_at).toLocaleString()}</Label><Label small>{row.summary.days} days · {row.summary.weights} weights · {row.summary.revisions} revisions</Label><Row><Button title="Preview restore" disabled={cloud.busy || state.mode !== 'real'} onPress={() => { void cloud.previewBackup(row.id); }} /><Button title="Delete snapshot" disabled={cloud.busy} onPress={() => Alert.alert('Delete cloud snapshot?', 'This permanently removes this backup. Local records are unchanged.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => { void cloud.removeBackup(row.id); } }])} /></Row></Card>)}
      <Button title="Sign out on this device" disabled={cloud.busy} onPress={() => { void cloud.signOut(); }} />
    </>}
    <Button title="Preview last local recovery" disabled={cloud.busy || state.mode !== 'real'} onPress={() => { void cloud.previewRecovery(); }} />
    {cloud.preview ? <Card><Label>{cloud.preview.local ? 'Local recovery' : 'Restore preview'}</Label><Label small>{cloud.preview.capturedAt}</Label><Label>{cloud.preview.summary.days} days · {cloud.preview.summary.weights} weights</Label><Label small>Replaces personal records and targets. Photos stay local. Existing records are saved locally before replacement. If local records change after this preview, restore stops.</Label><Row><Button title="Cancel" disabled={cloud.busy} onPress={cloud.cancelPreview} /><Button title="Restore this snapshot" primary disabled={cloud.busy} onPress={() => Alert.alert('Replace personal records?', 'Restore the previewed snapshot now? Your current personal records will be saved locally for recovery.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Restore', onPress: () => { void cloud.applyRestore(); } }])} /></Row></Card> : null}
  </Screen>;
}
