import React, { useEffect, useRef, useState } from 'react';
import { AccessibilityInfo, Animated, View, Pressable, Text } from 'react-native';
import { router } from 'expo-router';
import { useApp } from '../store/AppStore';
import { emptyDay, score, setAnswer, trend, twoWeeks } from '../domain/model';
import { milestoneProgress, periodSummary } from '../domain/progress';
import { Button, Card, Label, Row, Screen } from '../components/UI';
import { WeightChart } from '../components/WeightChart';
export default function Dashboard() {
  const { state, data, target, today, palette: p, updateData, ready } = useApp(); const day = data.days[today] ?? emptyDay(today, target); const displayedTarget = day.target ?? target; const [edit, setEdit] = useState(false); const current = trend(data.weights, today); const dates = twoWeeks(today); const left = day.calories == null || displayedTarget == null ? null : displayedTarget - day.calories;
  const period = periodSummary(data, today); const journey = milestoneProgress(data, state, today); const count = score(day).count;
  const [reduceMotion, setReduceMotion] = useState(true); const [pulse] = useState(() => new Animated.Value(1)); const previous = useRef({ today, mode: state.mode, count, ready });
  useEffect(() => { void AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion).catch(() => {}); const listener = AccessibilityInfo.addEventListener('reduceMotionChanged', setReduceMotion); return () => listener.remove(); }, []);
  useEffect(() => { const old = previous.current; previous.current = { today, mode: state.mode, count, ready }; if (reduceMotion) { pulse.stopAnimation(); pulse.setValue(1); return; } if (ready && old.ready && old.today === today && old.mode === state.mode && count > old.count) { const animation = Animated.sequence([Animated.timing(pulse, { toValue: 1.05, duration: 150, useNativeDriver: true }), Animated.timing(pulse, { toValue: 1, duration: 200, useNativeDriver: true })]); animation.start(); return () => animation.stop(); } }, [count, today, state.mode, ready, reduceMotion, pulse]);
  return <Screen title="ON TRACK" back={false}>
    <Row><Label small>{today} · {state.mode === 'demo' ? 'Demo' : 'Today'}</Label><Row><Button title={data.photos.length && !data.photoReviewedDates.includes(today) ? 'Review photo' : 'Photos'} primary={data.photos.length > 0 && !data.photoReviewedDates.includes(today)} onPress={() => router.push('/photos')} /><Button title="Settings" onPress={() => router.push('/settings')} /></Row></Row>
    {(['workout', 'creatine'] as const).map(key => day[key] === null || edit ? <Card key={key}><Row><Label>{key === 'workout' ? 'Workout today?' : 'Creatine taken?'}</Label><Row>{[true, false].map(value => <Button key={String(value)} title={value ? 'Yes' : 'No'} selected={day[key] === value} onPress={() => updateData(d => setAnswer(d, today, target, key, value))} />)}</Row></Row></Card> : null)}
    {day.workout !== null || day.creatine !== null ? <Row><Label small>{day.workout === true ? 'Workout ✓' : day.workout === false ? 'Workout: no' : ''} {day.creatine === true ? ' · Creatine ✓' : day.creatine === false ? ' · Creatine: no' : ''}</Label><Button title={edit ? 'Done' : 'Edit checks'} onPress={() => setEdit(!edit)} /></Row> : null}
    <Card><Row><Label>Today’s calories</Label><Button title="Details" onPress={() => router.push('/calories')} /></Row><Row><Text style={{ color: p.text, fontSize: 48, fontWeight: '800', fontVariant: ['tabular-nums'], letterSpacing: -1.5 }}>{day.calories?.toLocaleString() ?? '—'}</Text><Label small>{displayedTarget == null ? 'Set target in Settings' : `/ ${displayedTarget.toLocaleString()} kcal`}</Label></Row><View style={{ height: 11, borderRadius: 8, backgroundColor: p.grey, overflow: 'hidden' }}><View style={{ height: 11, width: `${day.calories != null && displayedTarget ? Math.min(100, day.calories / displayedTarget * 100) : 0}%`, backgroundColor: left != null && left < 0 ? p.red : p.primary }} /></View><Row><Label small>{left == null ? 'Enter today’s total' : `${Math.abs(left)} kcal ${left < 0 ? 'over target' : 'remaining'}`}</Label><Label small>{day.food === true ? 'Food logged ✓' : 'Log unconfirmed'}</Label></Row><Row><Button title="Update calories" onPress={() => router.push({ pathname: '/calories', params: { edit: 'yes' } })} /><Button title={day.food === true ? 'Confirmed ✓' : 'Everything I ate is logged'} primary disabled={day.food === true} onPress={() => router.push({ pathname: '/calories', params: { audit: 'yes' } })} /></Row></Card>
    <Card><Row><Label>Weight</Label><Button title="Details" onPress={() => router.push('/weight')} /></Row><Row><Label big>{current.average?.toFixed(1) ?? '—'}<Label small> lb</Label></Label><Label small>{journey.next === null ? journey.goal === null ? 'Goal not set' : 'Goal: '+journey.goal+' lb' : 'Next: '+journey.next+' lb'}</Label></Row><Label small>7-day average · {current.coverage}/7 days measured</Label><WeightChart /></Card>
    <Card><Row><Label>Two weeks</Label><Button title="Details" onPress={() => router.push('/progress')} /></Row><Row><Animated.Text style={{ color: p.primary, fontSize: 22, fontWeight: '800', transform: [{ scale: pulse }] }}>{count}/4 today</Animated.Text><Label small>{period.completeDays} all-done days</Label></Row><View style={{ flexDirection: 'row', gap: 4 }}>{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((name, i) => <View key={i} style={{ flex: 1, alignItems: 'center' }}><Label small>{name}</Label></View>)}</View>{[0, 7].map(offset => <View key={offset} style={{ flexDirection: 'row', gap: 4 }}>{dates.slice(offset, offset + 7).map(date => { const result = score(data.days[date] ?? emptyDay(date, target)); const future = date > today; const color = future ? p.bg : p[result.tone]; return <Pressable key={date} accessibilityRole="button" accessibilityLabel={`${date}, ${future ? 'future' : `${result.count} of four completed`}`} onPress={() => router.push({ pathname: '/day', params: { date } })} style={{ flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 10, borderWidth: 2, borderColor: date === today ? p.primary : 'transparent', backgroundColor: color }}><Text style={{ color: future || result.tone === 'grey' ? p.muted : p.bg, fontSize: 11 }}>{date.slice(-2)}</Text><Text style={{ color: future || result.tone === 'grey' ? p.text : p.bg, fontSize: 12, fontWeight: '800' }}>{future ? '—' : `${result.count}/4`}</Text></Pressable>; })}</View>)}<Label small>{dates[0].slice(5)} → {dates[13].slice(5)} · 4/4 complete · grey unknown</Label></Card>
  </Screen>;
}
