import React, { useState } from 'react';
import { Alert, Image, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Directory, File, Paths } from 'expo-file-system';
import { useApp } from '../store/AppStore';
import { Photo, makeId } from '../domain/model';
import { Button, Card, Label, Row, Screen } from '../components/UI';
export default function Photos() {
  const { data, today, updateData, state, palette: p } = useApp(); const [selectedId, setSelectedId] = useState<string | null>(null); const [mode, setMode] = useState<'Side by side' | 'Flip' | 'Overlay'>('Side by side'); const [flip, setFlip] = useState(false); const reviewed = data.photoReviewedDates.includes(today); const photos = data.photos.slice().sort((a, b) => a.date.localeCompare(b.date)); const reference = photos[0]; const selected = photos.find(photo => photo.id === selectedId) ?? photos[photos.length - 1];
  const add = async () => { try { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: false, quality: 1 }); if (result.canceled) return; const id = makeId(); const source = new File(result.assets[0].uri); const directory = new Directory(Paths.document, 'progress-photos', state.mode); await directory.create({ intermediates: true, idempotent: true }); const copy = new File(directory, `${id}.${source.extension.replace('.', '') || 'jpg'}`); await source.copy(copy); const photo: Photo = { id, date: today, uri: copy.uri, scale: 1, x: 0, y: 0 }; updateData(d => ({ ...d, photos: [...d.photos, photo] })); setSelectedId(id); } catch { Alert.alert('Could not add photo', 'The photo could not be copied into private app storage. Please try again.'); } };
  const align = (key: 'scale' | 'x' | 'y', delta: number) => { if (!selected) return; updateData(d => ({ ...d, photos: d.photos.map(photo => photo.id !== selected.id ? photo : { ...photo, [key]: key === 'scale' ? Math.max(.5, Math.min(2, photo.scale + delta)) : Math.max(-100, Math.min(100, photo[key] + delta)) }) })); };
  const picture = (photo: Photo | undefined) => photo ? <Image source={{ uri: photo.uri }} accessibilityLabel={`Progress photo ${photo.date}`} resizeMode="contain" style={{ width: '100%', height: '100%', transform: [{ translateX: photo.x }, { translateY: photo.y }, { scale: photo.scale }] }} /> : <Label small>No photo yet</Label>;
  return <Screen title="Progress photos"><Card><Label small>Private on this device. No upload or sharing.</Label><Button title="Add photo" primary onPress={add} />{!photos.length ? <Label small>Add a starting photo and a later photo to compare.</Label> : <><Row>{(['Side by side', 'Flip', 'Overlay'] as const).map(item => <Button key={item} title={item} selected={mode === item} onPress={() => setMode(item)} />)}</Row><View style={{ flexDirection: 'row', height: 320, gap: 8 }}>{mode === 'Side by side' ? <><View style={{ flex: 1, overflow: 'hidden', borderRadius: 12, backgroundColor: p.bg }}>{picture(reference)}</View><View style={{ flex: 1, overflow: 'hidden', borderRadius: 12, backgroundColor: p.bg }}>{picture(selected)}</View></> : <View style={{ flex: 1, overflow: 'hidden', borderRadius: 12, backgroundColor: p.bg }}>{picture(mode === 'Flip' && flip ? reference : selected)}{mode === 'Overlay' ? <View style={{ position: 'absolute', inset: 0, opacity: .5 }}>{picture(reference)}</View> : null}</View>}</View><Row><Label small>Start: {reference?.date}</Label><Label small>Compare: {selected?.date}</Label></Row>{mode === 'Flip' ? <Button title="Flip photo" onPress={() => setFlip(!flip)} /> : null}<Row>{photos.map(photo => <Button key={photo.id} title={photo.date} selected={photo.id === selected?.id} onPress={() => setSelectedId(photo.id)} />)}</Row><Button title={reviewed ? 'Photo reviewed ✓' : 'Mark photo reviewed'} onPress={() => updateData(d => ({ ...d, photoReviewedDates: [...new Set([...d.photoReviewedDates, today])] }))} /></>}</Card>{selected ? <Card><Label>Align comparison photo</Label><Label small>Uniform scale and position only. Original photo retained.</Label><Row><Button title="Smaller" onPress={() => align('scale', -.05)} /><Label>{Math.round(selected.scale * 100)}%</Label><Button title="Larger" onPress={() => align('scale', .05)} /></Row><Row><Button title="Left" onPress={() => align('x', -5)} /><Button title="Right" onPress={() => align('x', 5)} /><Button title="Up" onPress={() => align('y', -5)} /><Button title="Down" onPress={() => align('y', 5)} /></Row><Button title="Reset alignment" onPress={() => updateData(d => ({ ...d, photos: d.photos.map(photo => photo.id === selected.id ? { ...photo, scale: 1, x: 0, y: 0 } : photo) }))} /></Card> : null}</Screen>;
}
