import React, { useState } from 'react';
import { Alert, Share, View } from 'react-native';
import { router } from 'expo-router';
import { useApp } from '../store/AppStore';
import { dailyTasks, taskScore, taskSummary } from '../domain/dailyTasks';
import { milestoneProgress, periodSummary, shareSummary, TREND_COVERAGE, TrendRange } from '../domain/progress';
import { Button, Card, Label, Row, Screen } from '../components/UI';
import { ProgressBuddy } from '../components/ProgressBuddy';
import { buddyStatus } from '../domain/buddy';
import { WeightChart } from '../components/WeightChart';
export default function Progress() {
  const { data, state, today, palette:p }=useApp(); const [range,setRange]=useState<TrendRange>(28); const [preview,setPreview]=useState<string|null>(null); const buddy = buddyStatus(data, today); const period=periodSummary(data,today); const tasks=taskSummary(data,today); const weight=milestoneProgress(data,state,today);
  return <Screen title="Progress"><Card><Row><Label>Food consistency</Label><ProgressBuddy /></Row><Label small>{buddy.from} → {today}</Label><Label>{buddy.logged}/14 fully logged · {buddy.within}/{buddy.assessed} within target</Label><Label small>On track: at least 10 days logged with a target, and 80% within it. Mixed: at least 7 days reported. Off track: fewer than half of reported days within target. Below 7 reported days: checking in. Missing days earn no success.</Label><Label small>Weight fluctuations and rest days do not change this mood.</Label></Card><Card><Row><Label>Weight trend</Label><Button title="Weigh-ins" onPress={()=>router.push('/weight')}/></Row><Label big>{weight.current.average?.toFixed(1)??'—'}<Label small> lb</Label></Label><Label small>{weight.current.coverage}/7 days measured{weight.qualified?'':' · provisional'}</Label><Row>{([28,90,'all'] as const).map(r=><Button key={r} title={r==='all'?'All time':`${r} days`} selected={range===r} onPress={()=>setRange(r)}/>)}</Row><WeightChart range={range}/><Label small>7-day averages · gaps over seven days stay disconnected.</Label>{weight.fraction!==null?<><Row><Label>{Math.round(weight.fraction*100)}% to goal</Label><Label small>{weight.goal} lb</Label></Row><View style={{height:10,backgroundColor:p.grey,borderRadius:8,overflow:'hidden'}}><View style={{height:10,width:`${weight.fraction*100}%`,backgroundColor:p.primary}}/></View><Label small>From {weight.baseline?.toFixed(1)} lb trend · {weight.baselineDate}</Label></>:<Label small>Set a goal and record {TREND_COVERAGE} days in a seven-day window to establish a trend baseline.</Label>}<Row>{weight.milestones.map(n=><View key={n} style={{padding:10,borderRadius:14,borderWidth:1,borderColor:weight.reached.includes(n)?p.primary:p.line}}><Label accent={weight.reached.includes(n)}>{weight.reached.includes(n)?'✓ ':''}{n} lb</Label></View>)}</Row><Label small>Trend checkpoints use at least {TREND_COVERAGE}/7 measured days. Below that, estimates remain provisional. This is a display rule; no permanent awards yet.</Label></Card>
    <Card><Label>Previous + current week</Label><Label small>{period.dates[0]} → {today} · upcoming days excluded</Label><Row><Label big>{tasks.completeDays}</Label><Label>all-done days / {period.dates.length}</Label></Row>{tasks.totals.map(t=><View key={t.label} style={{gap:5}}><Row><Label>{t.label}</Label><Label>{t.done}/{t.days}</Label></Row><View style={{height:6,backgroundColor:p.grey,borderRadius:5}}><View style={{height:6,width:`${t.done/t.days*100}%`,backgroundColor:p.primary,borderRadius:5}}/></View><Label small>{t.known} reported · {t.unknown} unknown</Label></View>)}<Label small>The four checks match your daily tasks. Calorie targets are shown separately.</Label></Card>
    <Card><Label>Calories & corrections</Label><Label>{period.meanCompleteCalories===null?'—':Math.round(period.meanCompleteCalories).toLocaleString()} kcal average</Label><Label small>Only {period.completeCalorieDays} fully logged days included. This is observed intake, not a recommended target.</Label><Label>{period.revisionCount} corrections · {period.revisedDays} distinct days</Label><Label small>Corrections retain your history. Fully logged over-target days still earn the logging check.</Label></Card>
    <Card><Label>Day history</Label>{period.rows.slice().reverse().map(({date})=><Row key={date}><Button title={date} onPress={()=>router.push({pathname:'/day',params:{date}})}/><Label small>{taskScore(data,date).count}/4 · {dailyTasks(data,date).filter(c=>c.value===null).length} unknown</Label></Row>)}</Card>
    <Button title="Preview share summary" primary onPress={()=>setPreview(shareSummary(data,state,today))}/>{preview!==null?<Card><Label>Share preview</Label><Label small>{preview}</Label><Row><Button title="Cancel" onPress={()=>setPreview(null)}/><Button title="Open share sheet" primary onPress={()=>{void Share.share({message:preview}).catch(()=>Alert.alert('Could not open share sheet'));}}/></Row><Label small>You choose the recipient. No photos or automatic sharing.</Label></Card>:null}
  </Screen>;
}
