import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { useApp } from '../store/AppStore';
export function Label({ children, small = false, big = false, accent = false }: { children: React.ReactNode; small?: boolean; big?: boolean; accent?: boolean }) { const { palette: p } = useApp(); return <Text style={{ color: accent ? p.primary : small ? p.muted : p.text, fontSize: big ? 38 : small ? 12 : 16, fontWeight: big ? '800' : '500', fontVariant: ['tabular-nums'] }}>{children}</Text>; }
export function Row({ children }: { children: React.ReactNode }) { return <View style={styles.row}>{children}</View>; }
export function Button({ title, onPress, primary = false, selected = false, disabled = false }: { title: string; onPress: () => void; primary?: boolean; selected?: boolean; disabled?: boolean }) { const { palette: p } = useApp(); return <Pressable accessibilityRole="button" accessibilityState={{ disabled, selected }} disabled={disabled} onPress={onPress} style={({ pressed }) => ({ minHeight: 44, paddingHorizontal: 12, paddingVertical: 10, borderRadius: p.radius / 2, backgroundColor: primary || selected ? p.primary : p.bg, borderColor: p.line, borderWidth: primary ? 0 : 1, opacity: disabled ? .5 : pressed ? .7 : 1, justifyContent: 'center' })}><Text style={{ color: primary || selected ? p.bg : p.text, fontSize: 14, fontWeight: '700', textAlign: 'center' }}>{title}</Text></Pressable>; }
export function Card({ children }: { children: React.ReactNode }) { const { palette: p } = useApp(); return <View style={{ backgroundColor: p.tile, borderColor: p.line, borderWidth: 1, borderRadius: p.radius, padding: 14, gap: 9 }}>{children}</View>; }
export function Field({ value, onChangeText, placeholder, numeric = false }: { value: string; onChangeText: (s: string) => void; placeholder: string; numeric?: boolean }) { const { palette: p } = useApp(); return <TextInput accessibilityLabel={placeholder} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={p.muted} keyboardType={numeric ? 'decimal-pad' : 'default'} style={{ minHeight: 48, backgroundColor: p.bg, borderColor: p.line, borderWidth: 1, borderRadius: 12, padding: 12, color: p.text, fontSize: 18 }} />; }
export function Screen({ children, title, back = true }: { children: React.ReactNode; title: string; back?: boolean }) { const { palette: p, ready, error, state } = useApp(); return <SafeAreaView style={{ flex: 1, backgroundColor: p.bg }} edges={['top', 'bottom']}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 16, gap: 12, paddingBottom: 30 }}><Row>{back ? <Button title="‹ Back" onPress={() => router.back()} /> : null}<Label>{title}</Label>{state.mode === 'demo' ? <Label small>DEMO</Label> : null}</Row>{error ? <Text accessibilityRole="alert" style={{ color: p.red }}>{error}</Text> : null}{ready ? children : <Label>Loading…</Label>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' } });
