import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View, Platform } from 'react-native';
import Svg, { Defs, RadialGradient, Stop, Rect, Pattern, Path } from 'react-native-svg';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { PixelText, plainText } from './PixelText';
import { FantasyBackdrop } from './FantasyBackdrop';
import { useApp } from '../store/AppStore';
export function Label({ children, small = false, big = false, accent = false }: { children: React.ReactNode; small?: boolean; big?: boolean; accent?: boolean }) { const { palette: p } = useApp(); if (p.retro && !small) return <PixelText text={plainText(children)} color={accent ? p.primary : p.text} scale={big ? 4.5 : 1.8} />; return <Text style={{ color: accent ? p.primary : small ? p.muted : p.text, fontSize: big ? 38 : small ? 12 : 16, fontWeight: big ? '700' : '500', letterSpacing: p.fantasy && !small && !big ? .3 : 0, fontVariant: ['tabular-nums'] }}>{children}</Text>; }
export function Row({ children }: { children: React.ReactNode }) { return <View style={styles.row}>{children}</View>; }
export function Button({ title, onPress, primary = false, selected = false, disabled = false }: { title: string; onPress: () => void; primary?: boolean; selected?: boolean; disabled?: boolean }) { const { palette: p } = useApp(); return <Pressable accessibilityRole="button" accessibilityState={{ disabled, selected }} disabled={disabled} onPress={onPress} style={({ pressed }) => ({ minHeight: 44, paddingHorizontal: 12, paddingVertical: 10, borderRadius: p.radius / 2, borderTopLeftRadius: p.retro ? 0 : p.fantasy ? 12 : 6, borderBottomRightRadius: p.retro ? 0 : p.fantasy ? 12 : 6, backgroundColor: primary || selected ? p.primary : p.grey, borderColor: p.retro || p.fantasy ? p.accent : p.line, borderWidth: p.retro ? 2 : primary ? 0 : 1, opacity: disabled ? .5 : pressed ? .7 : 1, justifyContent: 'center' })}><View style={{ alignItems: 'center' }}><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }}>{p.fantasy ? <View style={{ width: 5, height: 5, backgroundColor: primary || selected ? p.bg : p.accent, transform: [{ rotate: '45deg' }] }} /> : null}<Text style={{ color: primary || selected ? p.bg : p.text, fontSize: p.retro ? 15 : p.fantasy ? 15 : 14, fontWeight: '700', fontFamily: p.retro ? Platform.OS === 'ios' ? 'Menlo' : 'monospace' : undefined, letterSpacing: p.retro ? .3 : 0, textAlign: 'center', flexShrink: 1 }}>{p.retro ? title.toUpperCase() : title}</Text>{p.fantasy ? <View style={{ width: 5, height: 5, backgroundColor: primary || selected ? p.bg : p.accent, transform: [{ rotate: '45deg' }] }} /> : null}</View></View></Pressable>; }
export function Card({ children, compact = false }: { children: React.ReactNode; compact?: boolean }) { const { palette: p } = useApp(); return <View style={{ backgroundColor: p.tile, borderColor: p.retro ? p.primary : p.line, borderWidth: p.retro ? 2 : 1, ...(p.retro ? { shadowColor: '#090616', shadowOffset: { width: 3, height: 4 }, shadowOpacity: 1, shadowRadius: 0, elevation: 4 } : {}), borderRadius: p.radius, borderTopLeftRadius: p.radius === 20 ? 6 : p.radius, borderBottomRightRadius: p.radius === 20 ? 6 : p.radius, padding: compact ? 10 : 14, gap: compact ? 6 : 9 }}>{compact ? null : p.fantasy ? <><View pointerEvents="none" style={{ position: 'absolute', inset: 3, borderWidth: 1, borderColor: p.primary, opacity: .22, borderRadius: 11 }} /><View pointerEvents="none" style={{ position: 'absolute', top: -1, left: 20, width: 48, height: 2, backgroundColor: p.primary }} /><View pointerEvents="none" style={{ position: 'absolute', bottom: -1, right: 20, width: 32, height: 2, backgroundColor: p.accent }} /></> : p.retro ? <><View pointerEvents="none" style={{ position: 'absolute', inset: 4, borderWidth: 1, borderColor: p.accent, opacity: .35 }} /><View style={{ flexDirection: 'row', gap: 4 }}>{[p.accent,p.primary,p.yellow,p.green].map(color => <View key={color} style={{ width: 5, height: 5, backgroundColor: color }} />)}</View></> : <View style={{ width: 36, height: 3, backgroundColor: p.accent, borderRadius: 2 }} />}{children}</View>; }
export function Field({ value, onChangeText, placeholder, numeric = false, autoFocus = false }: { value: string; onChangeText: (s: string) => void; placeholder: string; numeric?: boolean; autoFocus?: boolean }) { const { palette: p } = useApp(); return <TextInput autoFocus={autoFocus} selectTextOnFocus={autoFocus} accessibilityLabel={placeholder} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={p.muted} keyboardType={numeric ? 'decimal-pad' : 'default'} style={{ minHeight: 48, backgroundColor: p.bg, borderColor: p.line, borderWidth: p.retro ? 2 : 1, borderRadius: p.retro ? 0 : 12, padding: 12, color: p.text, fontSize: 18 }} />; }
export function Screen({ children, title, back = true, compact = false }: { children: React.ReactNode; title: string; back?: boolean; compact?: boolean }) { const { palette: p, ready, error, state } = useApp(); return <SafeAreaView style={{ flex: 1, backgroundColor: p.bg }} edges={back ? ['top', 'bottom'] : ['top']}><View pointerEvents="none" style={StyleSheet.absoluteFill}>{p.fantasy ? <FantasyBackdrop /> : <Svg width="100%" height="100%"><Defs>{p.retro ? <Pattern id="crtGrid" patternUnits="userSpaceOnUse" width={24} height={24}><Path d="M24 0H0V24" stroke={p.line} strokeWidth={.6} opacity={.4} /><Path d="M0 4H24M0 8H24M0 12H24M0 16H24M0 20H24" stroke={p.accent} strokeWidth={.3} opacity={.1} /></Pattern> : null}<RadialGradient id="ambient" cx="100%" cy="0%" r="85%"><Stop offset="0%" stopColor={p.accent} stopOpacity={0.18}/><Stop offset="100%" stopColor={p.bg} stopOpacity={0}/></RadialGradient></Defs><Rect width="100%" height="100%" fill="url(#ambient)" />{p.retro ? <Rect width="100%" height="100%" fill="url(#crtGrid)" /> : null}</Svg>}</View><ScrollView automaticallyAdjustKeyboardInsets keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: compact ? 12 : 16, gap: compact ? 8 : 12, paddingBottom: compact ? 12 : 30 }}>{title || back ? <Row>{back ? <Button title="‹ Back" onPress={() => router.back()} /> : null}<Text style={{ color: p.accent, fontSize: back ? 18 : 22, fontWeight: '700',  letterSpacing: back ? 0 : 2 }}>{title}</Text>{state.mode === 'demo' ? <Label small>DEMO</Label> : null}</Row> : null}{error ? <Text accessibilityRole="alert" style={{ color: p.red }}>{error}</Text> : null}{ready ? children : <Label>Loading…</Label>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' } });
