import React, { useEffect, useRef, useState } from 'react';
import { AccessibilityInfo, Animated, View, Pressable, Text } from 'react-native';
import { router } from 'expo-router';
import { useApp } from '../../store/AppStore';
import { confirmFood, emptyDay, score, setAnswer, trend, twoWeeks } from '../../domain/model';
import { milestoneProgress, periodSummary } from '../../domain/progress';
import { Button, Card, Label, Row, Screen } from '../../components/UI';
import Svg, { Defs, LinearGradient, Stop, Rect } from 'react-native-svg';
import { WeightChart } from '../../components/WeightChart';
export default function Dashboard() {
  const { state, data, target, today, palette: p, updateData, ready } = useApp(); const day = data.days[today] ?? emptyDay(today, target); const displayedTarget = day.target ?? target; const [edit, setEdit] = useState(false); const current = trend(data.weights, today); const dates = twoWeeks(today); const left = day.calories == null || displayedTarget == null ? null : displayedTarget - day.calories;
  const period = periodSummary(data, today); const journey = milestoneProgress(data, state, today); const count = score(day).count;
  const [reduceMotion, setReduceMotion] = useState(true); const [pulse] = useState(() => new Animated.Value(1)); const previous = useRef({ today, mode: state.mode, count, ready });
  useEffect(() => { void AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion).catch(() => {}); const listener = AccessibilityInfo.addEventListener('reduceMotionChanged', setReduceMotion); return () => listener.remove(); }, []);
  useEffect(() => { const old = previous.current; previous.current = { today, mode: state.mode, count, ready }; if (reduceMotion) { pulse.stopAnimation(); pulse.setValue(1); return; } if (ready && old.ready && old.today === today && old.mode === state.mode && count > old.count) { const animation = Animated.sequence([Animated.timing(pulse, { toValue: 1.05, duration: 150, useNativeDriver: true }), Animated.timing(pulse, { toValue: 1, duration: 200, useNativeDriver: true })]); animation.start(); return () => animation.stop(); } }, [count, today, state.mode, ready, reduceMotion, pulse]);
  return <Screen title="ON TRACK" back={false}>
    <Label small>{today}</Label>
    {(['workout', 'creatine'] as const).map(key => day[key] === null || edit ? <Card key={key}><Row><Label>{key === 'workout' ? 'Workout today?' : 'Creatine taken?'}</Label><Row>{[true, false].map(value => <Button key={String(value)} title={value ? 'Yes' : 'No'} selected={day[key] === value} onPress={() => updateData(d => setAnswer(d, today, target, key, value))} />)}</Row></Row></Card> : null)}
    {day.workout !== null || day.creatine !== null ? <Row><Label small>{day.workout === true ? 'Workout ✓' : day.workout === false ? 'Workout: no' : ''} {day.creatine === true ? ' · Creatine ✓' : day.creatine === false ? ' · Creatine: no' : ''}</Label><Button title={edit ? 'Done' : 'Edit checks'} onPress={() => setEdit(!edit)} /></Row> : null}
    <Card><Row><Label>Today’s calories</Label><Button title="Details" onPress={() => router.push('/calories')} /></Row><Row><Text style={{ color: p.text, fontSize: 42, fontWeight: '700', fontVariant: ['tabular-nums'], letterSpacing: -1.5 }}>{day.calories?.toLocaleString() ?? '—'}</Text><Label small>{displayedTarget == null ? 'Set target in Settings' : `/ ${displayedTarget.toLocaleString()} kcal`}</Label></Row><View style={{ height: 11, borderRadius: 8, backgroundColor: p.grey, overflow: 'hidden' }}><View style={{ height: 11, width: `${day.calories != null && displayedTarget ? Math.min(100, day.calories / displayedTarget * 100) : 0}%`, overflow: 'hidden' }}><Svg width="100%" height={11}><Defs><LinearGradient id="calorieFill" x1="0%" y1="0%" x2="100%" y2="0%"><Stop offset="0%" stopColor={left != null && left < 0 ? p.red : p.accent} /><Stop offset="100%" stopColor={left != null && left < 0 ? p.red : p.primary} /></LinearGradient></Defs><Rect width="100%" height={11} fill="url(#calorieFill)" /></Svg></View></View><Row><Label small>{left == null ? 'Enter today’s total' : `${Math.abs(left)} kcal ${left < 0 ? 'over target' : 'remaining'}`}</Label><Label small>{day.food === true ? 'Food logged ✓' : 'Food check pending'}</Label></Row><Row><Button title={day.calories == null ? "Add calories" : "Edit calories"} primary onPress={() => router.push({ pathname: '/calories', params: { edit: 'yes' } })} /><Button title={day.food === true ? '✓ Food logged' : '○ Food logged'} selected={day.food === true} disabled={day.calories == null} onPress={() => updateData(d => day.food === true ? setAnswer(d, today, target, 'food', null) : confirmFood(d, today, target))} /></Row></Card>
    <Card><Row><Label>Weight</Label><Button title={data.weights.some(w => w.date === today) ? "Edit weight" : "Add weight"} primary onPress={() => router.push('/weight')} /></Row><Row><Label big>{current.average?.toFixed(1) ?? '—'}<Label small> lb</Label></Label><Label small>{journey.next === null ? journey.goal === null ? 'Goal not set' : 'Goal: '+journey.goal+' lb' : 'Next: '+journey.next+' lb'}</Label></Row><Row><Label small>7-day average</Label><Label small>{data.weights.filter(w => w.date === today).length ? `Today: ${data.weights.filter(w => w.date === today).slice(-1)[0].pounds.toFixed(1)} lb` : `Weigh-in: ${state.weighInTime ?? '14:00'}`}</Label></Row><WeightChart /></Card>
    <Card><Row><Label>Two weeks</Label><Button title="Details" onPress={() => router.push('/progress')} /></Row><Row><Animated.Text style={{ color: p.primary, fontSize: 22, fontWeight: '800', transform: [{ scale: pulse }] }}>{count}/4 today</Animated.Text><Label small>{period.completeDays} all-done days</Label></Row><View style={{ flexDirection: 'row', gap: 4 }}>{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((name, i) => <View key={i} style={{ flex: 1, alignItems: 'center' }}><Label small>{name}</Label></View>)}</View>{[0, 7].map(offset => <View key={offset} style={{ flexDirection: 'row', gap: 4 }}>{dates.slice(offset, offset + 7).map(date => { const result = score(data.days[date] ?? emptyDay(date, target)); const future = date > today; const color = future ? p.bg : result.tone === 'yellow' ? p.yellowSurface ?? p.yellow : result.tone === 'red' ? p.redSurface ?? p.red : p[result.tone]; const cellText = result.tone === 'yellow' && p.yellowSurface ? p.yellow : result.tone === 'red' && p.redSurface ? p.red : p.bg; return <Pressable key={date} accessibilityRole="button" accessibilityLabel={`${date}, ${future ? 'future' : `${result.count} of four completed`}`} onPress={() => router.push({ pathname: '/day', params: { date } })} style={{ flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 10, borderWidth: 2, borderColor: date === today ? p.primary : 'transparent', backgroundColor: color }}><Text style={{ color: future || result.tone === 'grey' ? p.muted : cellText, fontSize: 11 }}>{date.slice(-2)}</Text><Text style={{ color: future || result.tone === 'grey' ? p.text : cellText, fontSize: 12, fontWeight: '800' }}>{future ? '—' : `${result.count}/4`}</Text></Pressable>; })}</View>)}<Label small>{dates[0].slice(5)} → {dates[13].slice(5)} · 4/4 complete · grey unknown</Label></Card>
  </Screen>;
}
