import React, { useState } from 'react';
import { Alert, Image, Platform, Share, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { Directory, File, Paths } from 'expo-file-system';
import { useApp } from '../../store/AppStore';
import { Photo, makeId } from '../../domain/model';
import { validDate } from '../../domain/reminders';
import { Button, Card, Field, Label, Row, Screen } from '../../components/UI';
export default function Photos() {
  const { data, today, updateData, commit, state, palette: p } = useApp(); const [selectedId, setSelectedId] = useState<string | null>(null); const [referenceId,setReferenceId]=useState<string|null>(null); const [mode, setMode] = useState<'Side by side' | 'Flip' | 'Slider'>('Side by side'); const [flip, setFlip] = useState(false); const [position,setPosition]=useState(50); const [width,setWidth]=useState(0); const [trackWidth,setTrackWidth]=useState(1); const [busy,setBusy]=useState(false); const [captureDate,setCaptureDate]=useState(today);
  const reviewed = data.photoReviewedDates.includes(today); const photos = data.photos.slice().sort((a,b)=>a.date.localeCompare(b.date)); const reference=photos.find(photo=>photo.id===referenceId)??photos[0]; const selected=photos.find(photo=>photo.id===selectedId)??photos[photos.length-1];
  const add=async()=>{ if (!validDate(captureDate) || captureDate > today) { Alert.alert('Choose a valid photo date today or earlier'); return; } setBusy(true); const modeAtPick=state.mode; let copied:File|null=null; try { const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:false,quality:1}); if(result.canceled)return; const id=makeId(); const source=new File(result.assets[0].uri); const directory=new Directory(Paths.document,'progress-photos',modeAtPick); directory.create({intermediates:true,idempotent:true}); copied=new File(directory,`${id}.${source.extension.replace('.','')||'jpg'}`); await source.copy(copied); const photo:Photo={id,date:captureDate,uri:copied.uri,scale:1,x:0,y:0}; await commit(s=>({...s,[modeAtPick]:{...s[modeAtPick],photos:[...s[modeAtPick].photos,photo]}})); setSelectedId(id); } catch { if(copied?.exists)try{copied.delete();}catch{} Alert.alert('Could not add photo','Please retry. The selected original is unchanged.'); } finally {setBusy(false);} };
  const align=(key:'scale'|'x'|'y',delta:number)=>{if(!selected)return;updateData(d=>({...d,photos:d.photos.map(photo=>photo.id!==selected.id?photo:{...photo,[key]:key==='scale'?Math.max(.5,Math.min(2,photo.scale+delta)):Math.max(-100,Math.min(100,photo[key]+delta))})}));};
  const picture=(photo:Photo|undefined)=>photo?<Image source={{uri:photo.uri}} accessibilityLabel={`Progress photo ${photo.date}`} resizeMode="contain" style={{width:'100%',height:'100%',transform:[{translateX:photo.x},{translateY:photo.y},{scale:photo.scale}]}}/>:<Label small>No photo yet</Label>;
  const remove=()=>{if(!selected)return;const photo=selected;const modeAtDelete=state.mode;Alert.alert('Delete app copy?',`Remove the ${photo.date} photo from ON TRACK. Your original in Photos is unchanged.`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>{void(async()=>{setBusy(true);try{await commit(s=>({...s,[modeAtDelete]:{...s[modeAtDelete],photos:s[modeAtDelete].photos.filter(item=>item.id!==photo.id)}}));try{const directory=new Directory(Paths.document,'progress-photos',modeAtDelete);const file=new File(photo.uri);if(!file.uri.startsWith(directory.uri.replace(/\/$/,'')+'/'))throw new Error('Not an app-owned photo path');if(file.exists)file.delete();}catch{Alert.alert('Photo removed from timeline','The app copy could not be deleted from disk. Secure deletion is not confirmed.');}setSelectedId(null);}catch{Alert.alert('Could not delete','Your photo remains in the timeline.');}finally{setBusy(false);}})();}}]);};
  const exportOriginal=()=>{if(!selected)return;const photo=selected;if(Platform.OS!=='ios'){Alert.alert('iPhone export only','File export on other platforms needs a native sharing adapter.');return;}Alert.alert('Export original photo?',`${photo.date} · alignment edits are excluded. Choose where to save or share the file.`,[{text:'Cancel',style:'cancel'},{text:'Open share sheet',onPress:()=>{void Share.share({url:photo.uri}).catch(()=>Alert.alert('Could not export photo'));}}]);};
  return <Screen title="Photos" back={false}><Card><Label small>Private app copies. Export only when you choose.</Label><Field value={captureDate} onChangeText={setCaptureDate} placeholder="Photo date YYYY-MM-DD" /><Button title={busy?'Working…':'Add photo'} primary disabled={busy} onPress={()=>{void add();}}/>{!photos.length?<Label small>Add a starting photo and a later photo to compare.</Label>:<><Row>{(['Side by side','Flip','Slider']as const).map(item=><Button key={item} title={item} selected={mode===item} onPress={()=>{setMode(item);setFlip(false);}}/>)}</Row>
    <View onLayout={event=>setWidth(event.nativeEvent.layout.width)} style={{flexDirection:'row',height:320,gap:8}}>{mode==='Side by side'?<><View style={{flex:1,overflow:'hidden',borderRadius:12,backgroundColor:p.bg}}>{picture(reference)}</View><View style={{flex:1,overflow:'hidden',borderRadius:12,backgroundColor:p.bg}}>{picture(selected)}</View></>:<View style={{flex:1,overflow:'hidden',borderRadius:12,backgroundColor:p.bg}}>{picture(mode==='Flip'&&flip?reference:selected)}{mode==='Slider'?<><View style={{position:'absolute',top:0,bottom:0,left:0,width:`${position}%`,overflow:'hidden'}}><View style={{width,height:'100%'}}>{picture(reference)}</View></View><View pointerEvents="none" style={{position:'absolute',left:`${position}%`,top:0,bottom:0,width:2,backgroundColor:p.primary}}/></>:null}</View>}</View>
    <Row><Label small>Reference: {reference?.date}</Label><Label small>Compare: {selected?.date}</Label></Row>{mode==='Flip'?<Button title={flip?'Show comparison':'Show reference'} onPress={()=>setFlip(!flip)}/>:null}{mode==='Slider'?<><Label small>Drag to compare · {Math.round(position)}% reference</Label><View accessible accessibilityRole="adjustable" accessibilityLabel="Photo comparison divider" accessibilityValue={{min:0,max:100,now:Math.round(position)}} accessibilityActions={[{name:'increment',label:'More reference photo'},{name:'decrement',label:'More comparison photo'}]} onAccessibilityAction={event=>setPosition(n=>Math.max(0,Math.min(100,n+(event.nativeEvent.actionName==='increment'?10:-10))))} onLayout={event=>setTrackWidth(event.nativeEvent.layout.width)} onStartShouldSetResponder={()=>true} onResponderGrant={event=>setPosition(Math.max(0,Math.min(100,event.nativeEvent.locationX/trackWidth*100)))} onResponderMove={event=>setPosition(Math.max(0,Math.min(100,event.nativeEvent.locationX/trackWidth*100)))} style={{height:44,justifyContent:'center'}}><View pointerEvents="none" style={{height:6,backgroundColor:p.grey,borderRadius:3}}><View style={{height:6,width:`${position}%`,backgroundColor:p.primary,borderRadius:3}}/></View><View pointerEvents="none" style={{position:'absolute',left:`${position}%`,marginLeft:-10,width:20,height:20,borderRadius:10,backgroundColor:p.primary}}/></View><Row><Button title="More reference" onPress={()=>setPosition(n=>Math.min(100,n+10))}/><Button title="More comparison" onPress={()=>setPosition(n=>Math.max(0,n-10))}/></Row></>:null}
    <Label small>Comparison photo</Label><Row>{photos.map(photo=><Button key={photo.id} title={photo.date} selected={photo.id===selected?.id} onPress={()=>{setSelectedId(photo.id);setFlip(false);}}/>)}</Row><Label small>Reference photo</Label><Row>{photos.map(photo=><Button key={photo.id} title={photo.date} selected={photo.id===reference?.id} onPress={()=>setReferenceId(photo.id)}/>)}</Row><Button title={reviewed?'Photo reviewed ✓':'Mark photo reviewed'} disabled={reviewed} onPress={()=>updateData(d=>({...d,photoReviewedDates:[...new Set([...d.photoReviewedDates,today])]}))}/></>}</Card>
    {selected?<><Card><Label>Align comparison photo</Label><Label small>Uniform scale and position only. Original retained.</Label><Row><Button title="Smaller" onPress={()=>align('scale',-.05)}/><Label>{Math.round(selected.scale*100)}%</Label><Button title="Larger" onPress={()=>align('scale',.05)}/></Row><Row><Button title="Left" onPress={()=>align('x',-5)}/><Button title="Right" onPress={()=>align('x',5)}/><Button title="Up" onPress={()=>align('y',-5)}/><Button title="Down" onPress={()=>align('y',5)}/></Row><Button title="Reset alignment" onPress={()=>updateData(d=>({...d,photos:d.photos.map(photo=>photo.id===selected.id?{...photo,scale:1,x:0,y:0}:photo)}))}/></Card><Card><Button title="Export selected original" disabled={busy} onPress={exportOriginal}/><Button title="Delete selected app copy" disabled={busy} onPress={remove}/><Label small>Export and deletion are explicit. They do not change your system photo library.</Label></Card></>:null}
  </Screen>;
}
